### ISSUE TITLE
Refine tick values on discrete x axes.

### ISSUE THREAD

**Issue by riga** [columnflow/columnflow#207]
The values at ticks on the x axis for variables that have `discrete_x` defined are currently just derived from `bin_edges` which can lead to too many ticks being shown.

This [this comment](https://github.com/uhh-cms/columnflow/pull/206#pullrequestreview-1320412974) for more info.

**Comment by pkausw** [comment]
@riga you mentioned yesterday that this issue is resolved. Can we close this issue then? Which PR closed it?

**Comment by riga** [comment]
Oh, I might have confused things. The variable definition already allows setting `discrete_x`, it's just not picked up by the plotting yet, so the issue is not fully resolved yet.
